### ISSUE TITLE
Virus distribution

### ISSUE THREAD

**Issue by Serverfrog** [Darian11111/TempleWin-Valorant#1]
@Nick-Vinesmoke, your Donation link is used here in the repo, and most likely in many other ones

**Comment by Nick-Vinesmoke** [comment]
Why somebody uses my donation link? This is original (https://github.com/Nick-Vinesmoke/The-Murk-stealer)

**Comment by Serverfrog** [comment]
so its your shit that spams up github with the bot upvoted repositories?

**Comment by Nick-Vinesmoke** [comment]
What bot I can't understand? What I should do?

**Comment by Serverfrog** [comment]
![image](https://user-images.githubusercontent.com/1306404/232038915-94452e26-cf3d-4246-b05b-8af52bfd740a.png)
If you sort for Repositories that get the most stars today, you will see things like that: Repos created to pretend that they are Game Hacks or others, all using your Donation link, and if the reason is that they are using your tool.. well then that is what they include.

What should you do? i don't know. My standpoint is, that these kind of easy to use Stealer should be a bit more complex to use or hidden completly... but im not a red team player in that way.

**Comment by Nick-Vinesmoke** [comment]
link to donate me not to carry malicious content
